### ISSUE TITLE
蓝牙与麦克风不驱动

### ISSUE THREAD

**Issue by GYSakura** [Xhichn/Hackbook_Redmi_G#4]
蓝牙打不开，系统偏好设置里也没有蓝牙选项。系统信息蓝牙为“未找到信息。”
麦克风可以在设置里看到，但是没有声音。
尝试过重新安装IntelBluetoothFirmware.kext和AppleALC.kext
机器是i7-10750H的

**Comment by Xhichn** [comment]
目前EFI的USB定制存在问题，会在不久之后修复

声卡其实还没有完全弄好，不过内建麦克风由于使用了英特尔智音技术，不可用

**Comment by Xhichn** [comment]
最新的 Release 已经修复了蓝牙，可以尝试一下

**Comment by Xhichn** [comment]
> 蓝牙打不开，系统偏好设置里也没有蓝牙选项。系统信息蓝牙为“未找到信息。”
> 麦克风可以在设置里看到，但是没有声音。
> 尝试过重新安装IntelBluetoothFirmware.kext和AppleALC.kext
> 机器是i7-10750H的

经过讨论之后，由于声卡搭载了英特尔智音技术，估计短时间内不会有麦克风支持了
